name: 11 - Inputs
on:
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        default: false
        description: "Skip deployment and only print build output"
      target:
        type: environment
        required: true
        description: "Skip deployment and only print build output"
      tag:
        type: choice
        options:
          - 'v1'
          - 'v2'
          - 'v3'
        default: 'v3'
        description: "Release from which to build and deploy"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Build"
        run: echo "Building from tag ${{ inputs.tag }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ inputs.target }}
    if: ${{ inputs.dry_run == false }}
    steps:
      - name: "Deploy"
        run: echo "Deploying to ${{ inputs.target }}"