name: 13 - Caching
on: 
  workflow_dispatch:
    inputs:
      use-cache:
        type: boolean
        default: true
        description: "Whether to cache or not"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the code" 
        uses: checkout@v4

      - name: "Setup Node"
        uses: setup-node@v4
        with: 
          node-version: "20.x"

      - name: "Install dependencies"
        working-directory: 13-caching/react-app
        run: |
          npm ci

      - name: "Testing"
        working-directory: 13-caching/react-app
        run: |
          npm run test

      - name: "Building"
        working-directory: 13-caching/react-app
        run: |
          npm run build

      - name: "Deploying to nonprod"
        run: |
          echo "Deploying to nonprod"