name: 13 - Caching
on: 
  workflow_dispatch:
    inputs:
      use-cache:
        type: boolean
        default: true
        description: "Whether to cache or not"
      node-version:
        type: choice
        options:
          - 18.x
          - 20.x
          - 21.x
        default: 20.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the code" 
        uses: actions/checkout@v4

      - name: "Setup Node"
        uses: actions/setup-node@v4
        with: 
          node-version: "20.x"

      - name: "Download Cached dependencies"
        id: cache
        if: ${{ inputs.use-cache == true }}
        uses: actions/cache@v3
        with:
          path: "13-caching/react-app/node_modules"
          key: "deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}"

      - name: "Install dependencies"
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: 13-caching/react-app
        run: |
          npm ci

      - name: "Testing"
        working-directory: 13-caching/react-app
        run: |
          npm run test

      - name: "Building"
        working-directory: 13-caching/react-app
        run: |
          npm run build

      - name: "Deploying to nonprod"
        run: |
          echo "Deploying to nonprod"