name: 18 - 1 - Reusable Workflows - Reusable Definition
on: 
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: "hello-world"
        run: echo "hello-world"
      